baseURL = "https://blog.astares.com/"
title = "Astares Blog"
author = "Torsten Bergmann"
copyright = "astares.com"
paginate = 10
languageCode = "en"
theme = "tailwind"

[markup]
  _merge = "deep"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "logo.svg"

  [params.footer]
    since = 2000
    poweredby = false

[menu]

  [[menu.main]]
    identifier = "main"
    name = "astares.com"
    url = "https://www.astares.com"
    weight = 10

  [[menu.main]]
    identifier = "home"
    name = "Home"
    pageRef = "/"
    weight = 20

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 30

  [[menu.main]]
    identifier = "brand"
    name = "Brand"
    url = "https://www.figma.com/design/xSIGYJl76tP42hpG1Iaca1/ASTARES?node-id=0-1&t=1AAwDaTyGG5FZLUI-1"
    weight = 40

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://about.astares.com"
    weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"